# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20160419_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empsalary',
            old_name='emp_name',
            new_name='emp_name1',
        ),
    ]
