# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20160419_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empsalary',
            options={'managed': False},
        ),
    ]
