# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20160419_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empsalary',
            options={'managed': True},
        ),
    ]
