# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20160419_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empsalary',
            old_name='emp_name1',
            new_name='salery',
        ),
    ]
