# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20160419_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empsalary',
            old_name='salery',
            new_name='hgfd',
        ),
    ]
